import Image from "next/image";

export default function Home() {
  return (
    <main></main>
  // <main>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  //   <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit, earum blanditiis excepturi quo repellendus ipsa rem iste similique nemo quae. Numquam qui inventore quisquam cum doloremque debitis quidem neque accusamus.</p>
  // </main>
  );
}
